"""empty message

Revision ID: 2a6e52907c58
Revises: 344f109610ad
Create Date: 2022-02-07 19:10:23.652330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6e52907c58'
down_revision = '344f109610ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('country', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'actor', 'country', ['country'], ['name'], ondelete='cascade')
    op.add_column('director', sa.Column('country', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'director', 'country', ['country'], ['name'], ondelete='cascade')
    op.drop_constraint('film_country_fkey', 'film', type_='foreignkey')
    op.drop_column('film', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('film_country_fkey', 'film', 'country', ['country'], ['name'], ondelete='CASCADE')
    op.drop_constraint(None, 'director', type_='foreignkey')
    op.drop_column('director', 'country')
    op.drop_constraint(None, 'actor', type_='foreignkey')
    op.drop_column('actor', 'country')
    # ### end Alembic commands ###
