"""empty message

Revision ID: 6b9e24125fd3
Revises: c7225207d4df
Create Date: 2022-02-14 18:54:05.598773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9e24125fd3'
down_revision = 'c7225207d4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('review_header', sa.Text(), nullable=True))
    op.alter_column('user_films', 'user',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_films', 'user',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('review', 'review_header')
    # ### end Alembic commands ###
