"""empty message

Revision ID: 7fe8edbf1ab1
Revises: 8d5a33d9af69
Create Date: 2022-02-05 19:53:38.106163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe8edbf1ab1'
down_revision = '8d5a33d9af69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
