"""empty message

Revision ID: c7225207d4df
Revises: 2a6e52907c58
Create Date: 2022-02-07 22:14:14.779130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7225207d4df'
down_revision = '2a6e52907c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'description')
    # ### end Alembic commands ###
